use hibernate;
drop database hibernate;
create database hibernate;
show tables;
drop table developers;
drop table computer;
select * from  developers;
select * from computer_developers;
select * from computer; 
select * from people;
select * from laptop;
drop database hibernate;
use music;
