Use hibernate;
show tables;
drop table adithi;
drop table adithya;
drop table student;
select * from laptop;
select * from student; 
describe table laptop;
describe laptop;
describe student;
select * from laptop_student;
select * from student_laptop;
drop table professor;
drop table professor_department;
drop table department;
SELECT * FROM professor;
SELECT * FROM Department;
SELECT * FROM workers;	
SELECT * from employee;
drop table workers;
SELECT * FROM workers_car;
SELECT * FROM car;