SELECT first_name AS Your_name,last_name AS father_name FROM employee ;
SELECT DISTINCT branch_id,sex FROM employee;
SELECT COUNT(sex) FROM employee;
SELECT COUNT(DISTINCT sex) FROM employee;
SELECT * FROM employee ;
SELECT COUNT(sex) from employee;
SELECT AVG(salary) FROM employee;
SELECT COUNT(*) AS Sex FROM (SELECT DISTINCT sex FROM employee);
SELECT sex FROM employee WHERE sex='M';
SELECT * FROM employee WHERE first_name BETWEEN 'David' AND 'andy' LIMIT 2;
ALTER TABLE employee DROP COLUMN sex;
DELETE FROM employee WHERE first_name='David' ;
ALTER TABLE employee ADD sex VARCHAR(1);
SELECT * FROM employee WHERE NOT first_name='David';
SELECT * FROM employee WHERE salary = 75 AND (sex='M' OR sex ='F');
SELECT first_name,last_name FROM employee ORDER BY first_name,last_name;
UPDATE employee SET sex='M' WHERE branch_id=2;
CREATE DATABASE techWebsiteDatabase;
CREATE TABLE userData(userName VARCHAR(20) PRIMARY KEY,passWord VARCHAR(20));
INSERT INTO userData VALUE('DharaniKavin','Dharani');
SELECT *FROM userData;
CREATE TABLE websiteTable(userName VARCHAR(30) PRIMARY KEY,passWord VARCHAR(20),name VARCHAR(15),date_id DATE,age INT,gamil VARCHAR(40));